export { authAPI } from './auth'
export { usersAPI } from './users'
export { votersAPI } from './voters'
export { electionsAPI } from './elections'
export { ssgElectionsAPI } from './ssgElections'
export { departmentalElectionsAPI } from './departmentalElections'
export { departmentsAPI } from './departments'
export { degreesAPI } from './degrees'
export { auditLogsAPI } from './auditLogs'
export { chatSupportAPI } from './chatSupport'
export { dashboardAPI } from './dashboard'
export { candidatesAPI } from './candidates'
export { positionsAPI } from './positions'
export { partylistsAPI } from './partylists'
export { ballotAPI } from './ballots'
export { votingAPI } from './voting'
export { electionParticipationAPI } from './electionParticipation'
export { healthAPI } from './health'

// Re-export the main api instance
export { default as api } from '../api'